<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,-8,1,'5YWz5LqO5aSn6bG8');
$cfg_Cs[2]=array(1,1,1,'5aSn6bG8566A5LuL');
$cfg_Cs[3]=array(1,1,1,'5aSn6bG85pWF5LqL');
$cfg_Cs[4]=array(0,1,1,'5pWZ5biI5Zui6Zif');
$cfg_Cs[5]=array(0,1,1,'5L2c5ZOB');
$cfg_Cs[6]=array(5,2,1,'57Sg5o+P');
$cfg_Cs[7]=array(5,2,1,'6Imy5b2p');
$cfg_Cs[8]=array(5,2,1,'6YCf5YaZ');
$cfg_Cs[9]=array(0,1,1,'5oub55Sf566A56ug');
$cfg_Cs[10]=array(0,2,1,'55S75a6k546v5aKD');
$cfg_Cs[11]=array(0,1,1,'6L6J54WM5oiQ57up');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
?>