
<field:name itemname="用户名" autofield="1" type="text" isnull="true" default=""  maxlength="24" page="">
</field:name>

<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="12" page="">
</field:tel>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="64" page="">
</field:email>

<field:content itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
