<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180731/1-1PI1105431.jpg ",93,251);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/180731/1-1PI1105431.jpg";
$z[1][4]['text']="唐老师色彩";
$z[1][4]['width']="640";
$z[1][4]['height']="541";
$z[2]=Array("img"," /uploads/allimg/180731/1-1PI1105432.jpg ",253,411);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/180731/1-1PI1105432.jpg";
$z[2][4]['text']="唐老师色彩";
$z[2][4]['width']="640";
$z[2][4]['height']="533";
$z[3]=Array("img"," /uploads/allimg/180731/1-1PI1105435.jpg ",413,571);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/180731/1-1PI1105435.jpg";
$z[3][4]['text']="唐老师色彩";
$z[3][4]['width']="640";
$z[3][4]['height']="552";

?>