<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180731/1-1PI1105610.jpg ",93,251);
$z[1][4]['ddimg']="/uploads/allimg/180731/1-1PI1105610.jpg";
$z[1][4]['text']="陈老师素描";
$z[1][4]['width']="640";
$z[1][4]['height']="945";
$z[2]=Array("img"," /uploads/allimg/180731/1-1PI1105612.jpg ",253,411);
$z[2][4]['ddimg']="/uploads/allimg/180731/1-1PI1105612.jpg";
$z[2][4]['text']="陈老师素描";
$z[2][4]['width']="640";
$z[2][4]['height']="919";
$z[3]=Array("img"," /uploads/allimg/180731/1-1PI1105614.jpg ",413,571);
$z[3][4]['ddimg']="/uploads/allimg/180731/1-1PI1105614.jpg";
$z[3][4]['text']="陈老师素描";
$z[3][4]['width']="640";
$z[3][4]['height']="890";
$z[4]=Array("img"," /uploads/allimg/180731/1-1PI1105616.jpg ",573,731);
$z[4][4]['ddimg']="/uploads/allimg/180731/1-1PI1105616.jpg";
$z[4][4]['text']="陈老师素描";
$z[4][4]['width']="640";
$z[4][4]['height']="931";

?>