{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/180731/1-1PI1105610.jpg' text='陈老师素描' width='640' height='945'} /uploads/allimg/180731/1-1PI1105610.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180731/1-1PI1105612.jpg' text='陈老师素描' width='640' height='919'} /uploads/allimg/180731/1-1PI1105612.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180731/1-1PI1105614.jpg' text='陈老师素描' width='640' height='890'} /uploads/allimg/180731/1-1PI1105614.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180731/1-1PI1105616.jpg' text='陈老师素描' width='640' height='931'} /uploads/allimg/180731/1-1PI1105616.jpg {/dede:img}
